name: 'Autonomous Holdings, LLC'
favicon: null
layout_spectrum: 0.98571
typography_spectrum: 0.61474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#12171b'
    - '#cdcdcd'
    - '#909090'
    - '#6e6e6e'
  brandStrength: 0.7029630239121616
  lightness: 0.20122509286738932
  saturation: 0.046150002628564835
  rhythmicContrast: 0.21944221784360707
purpose: []
