name: 'Autonomous Holdings, LLC'
favicon: null
layout_spectrum: 0.8494098917581141
typography_spectrum: 0.23370944242924452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7029630239121616
  lightness: 0.20122509286738932
  saturation: 0.046150002628564835
  rhythmicContrast: 0.21944221784360707
purpose: []
